#Sensitive iLink session - do not commit
#Thu Jul 23 14:59:24 GMT+08:00 2026
accountId=1a38b78038a1@im.bot
baseUrl=https\://ilinkai.weixin.qq.com
cursor=ChAIThDUqtHt+DMY5p2TvPgzEjoxYTM4Yjc4MDM4YTFAaW0uYm90OjA2MDAwMDVkNzJjMzQ2YTc0YzRkY2VmNmY2ZjAzNTlkNDllYjA1
token=1a38b78038a1@im.bot\:0600005d72c346a74c4dcef6f6f0359d49eb05
userId=o9cq801AU49g2EBiO64P1yYUt8CQ@im.wechat
